Add LatinX News
SECQUOIA/SECQUOIA.github.io pull request #11
Opened 2023-09-28 00:46 UTC by andres9403

Adding news about the LatinXinChE award

2023-09-28 15:10 UTC, bernalde requested changes
Small changes! Will post on LinkedIn and @ZedongPeng on the Engineering website!

2023-09-28 15:10 UTC, bernalde commented on _posts/2023-09-27 LatinX.md
> +We are pleased to announce that our both visiting scholars [Andres](https://SECQUOIA.github.io/2-members.html) and [Pedro](https://SECQUOIA.github.io/2-members.html) have been awarded in the **1st [L
```suggestion
We are pleased to announce that both our visiting scholars [Andres](https://SECQUOIA.github.io/2-members.html) and [Pedro](https://SECQUOIA.github.io/2-members.html) have received awards in the **1st [LatinXinChE Virtual Symposium](https://www.linkedin.com/posts/latinxinche_hispanicheritagemonth-latinxinche-activity-7110006993557323776-3gb9)**.
Pedro and Andres were the only finalists who were not faculty or Ph.D. candidates. Yet, Andres got the highest award, allowing him to talk at AIChE and fund his visit to Orlando. Pedro got a memorable mention and a monetary prize!
```

2023-09-28 15:10 UTC, bernalde commented on _posts/2023-09-27 LatinX.md
> +More than 50 scientist from all around the world 🌐 shared their cutting-edge researches. We want to thank you [LatinXinChE](https://twitter.com/LatinXinChE) for this great opportunity to share our wo
```suggestion
More than 50 scientists from all around the world 🌐 shared their cutting-edge research. Thank you [LatinXinChE](https://www.aiche.org/community/sites/committees/minority-affairs/latinx-che) for this excellent opportunity to share our work!
```

2023-09-28 15:12 UTC, ZedongPeng commented
No problem. I will update the Engineering website.

2023-09-29 22:47 UTC, bernalde approved these changes

2023-09-29 22:47 UTC, merged

2023-10-08 18:23 UTC, ZedongPeng commented
The post doesn't appear on the group website. Try to replace the blank in the file name.  @andres9403 
`2023-09-27 LatinX.md` to `2023-09-27-LatinX.md`.

2023-10-08 18:42 UTC, ZedongPeng commented
The engineering website updated.