Add informs news
SECQUOIA/SECQUOIA.github.io pull request #12
Opened 2023-10-23 20:37 UTC by ZedongPeng

- Add informs news
- Fix the LatinX bug

2023-10-23 23:01 UTC, bernalde requested changes

2023-10-23 23:01 UTC, bernalde commented on _posts/2023-10-18-INFORMS.md
> +We wrap up our first INFORMS annual meeting.
```suggestion
We wrapped up our first INFORMS annual meeting. 
```

2023-10-23 23:01 UTC, bernalde commented on _posts/2023-10-18-INFORMS.md
> +- [Zedong Peng](https://SECQUOIA.github.io/2-members.html) presenting the work on open-source discrete nonlinear optimizer [**MindtPy**](https://pyomo.readthedocs.io/en/stable/contributed_packages/mi
```suggestion
- [Zedong Peng](https://SECQUOIA.github.io/2-members.html) presented the work on open-source discrete nonlinear optimizer [**MindtPy**](https://pyomo.readthedocs.io/en/stable/contributed_packages/mindtpy.html). 
```

2023-10-23 23:01 UTC, bernalde commented on _posts/2023-10-18-INFORMS.md
> +- [David Esteban Bernal Neira](https://secquoia.github.io/1-bernalde.html) chairing the session on **hybrid classical quantum algorithms for optimization** !
```suggestion
- [David Esteban Bernal Neira](https://secquoia.github.io/1-bernalde.html) chaired the session on **hybrid classical quantum algorithms for optimization** !
```
and presented as well.

2023-10-24 03:52 UTC, ZedongPeng commented
The post has been modified according to the comments. @bernalde

2023-10-24 14:47 UTC, merged