add lines for orcid icon and add orcid for yirang
SECQUOIA/SECQUOIA.github.io pull request #37
Opened 2024-07-01 20:24 UTC by parkyr

Branch to add ORCID for members.md

2024-07-01 20:25 UTC, ZedongPeng commented
Great Job!

2024-07-01 20:46 UTC, ZedongPeng commented
Just added mine as well.

2024-07-02 21:10 UTC, bernalde requested changes
This has conflicts with main and needs to add at least placeholders for those that have not updated their ORCID

2024-07-03 16:55 UTC, bernalde approved these changes

2024-07-03 16:55 UTC, merged